-- 010 将浅色/深色主题语义颜色纳入系统变量管理。
-- INSERT IGNORE 仅补齐缺失项，保留已有安装中的管理员自定义值。

ALTER TABLE `system_variable`
  MODIFY COLUMN `color` VARCHAR(100) DEFAULT NULL COMMENT '显示颜色（前端使用）';

INSERT IGNORE INTO `system_variable`
  (`variable_key`, `variable_name`, `variable_type`, `variable_value`, `variable_label`, `sort_order`, `is_default`, `is_enabled`, `color`, `icon`) VALUES
('brand_primary', '品牌主色', 'theme_color_light', '#0f6cbd', '主按钮、选中态和主要链接', 10, 0, 1, NULL, NULL),
('brand_primary_hover', '主色悬停', 'theme_color_light', '#115ea3', '主要操作的悬停状态', 20, 0, 1, NULL, NULL),
('brand_primary_pressed', '主色按下', 'theme_color_light', '#0c3b5e', '主要操作的按下状态', 30, 0, 1, NULL, NULL),
('brand_cyan', '品牌青色', 'theme_color_light', '#00b7c3', '辅助品牌色和渐变终点', 40, 0, 1, NULL, NULL),
('brand_violet', '品牌紫色', 'theme_color_light', '#7160e8', '强调装饰和数据视觉辅助色', 50, 0, 1, NULL, NULL),
('primary_gradient_start', '渐变起点', 'theme_color_light', '#0f6cbd', '主品牌渐变的起始颜色', 60, 0, 1, NULL, NULL),
('primary_gradient_end', '渐变终点', 'theme_color_light', '#00b7c3', '主品牌渐变的结束颜色', 70, 0, 1, NULL, NULL),
('color_success', '成功色', 'theme_color_light', '#107c10', '成功、完成和正常状态', 110, 0, 1, NULL, NULL),
('color_warning', '警告色', 'theme_color_light', '#f7630c', '提醒、等待和风险状态', 120, 0, 1, NULL, NULL),
('color_danger', '危险色', 'theme_color_light', '#c50f1f', '失败、删除和高风险状态', 130, 0, 1, NULL, NULL),
('color_info', '信息色', 'theme_color_light', '#0078d4', '一般信息和辅助提示', 140, 0, 1, NULL, NULL),
('bg_body', '页面背景', 'theme_color_light', '#eef4fb', '应用主内容区的底色', 210, 0, 1, NULL, NULL),
('bg_card', '卡片背景', 'theme_color_light', 'rgba(255, 255, 255, 0.78)', '常规卡片和容器背景', 220, 0, 1, NULL, NULL),
('bg_card_hover', '卡片悬停', 'theme_color_light', 'rgba(255, 255, 255, 0.94)', '可交互卡片的悬停背景', 230, 0, 1, NULL, NULL),
('bg_overlay', '遮罩背景', 'theme_color_light', 'rgba(244, 248, 253, 0.78)', '浮层后方的半透明遮罩', 240, 0, 1, NULL, NULL),
('surface_solid', '实色表面', 'theme_color_light', '#ffffff', '输入框、弹层等不透明表面', 250, 0, 1, NULL, NULL),
('surface_mica', '云母表面', 'theme_color_light', 'rgba(242, 247, 252, 0.82)', '页面级柔和半透明材质', 260, 0, 1, NULL, NULL),
('surface_acrylic', '亚克力表面', 'theme_color_light', 'rgba(255, 255, 255, 0.68)', '浮动卡片和导航半透明材质', 270, 0, 1, NULL, NULL),
('text_primary', '主要文字', 'theme_color_light', '#17202b', '标题和高强调正文', 310, 0, 1, NULL, NULL),
('text_regular', '常规文字', 'theme_color_light', '#354052', '正文和表单内容', 320, 0, 1, NULL, NULL),
('text_secondary', '次要文字', 'theme_color_light', '#5c6675', '说明、辅助信息和元数据', 330, 0, 1, NULL, NULL),
('text_placeholder', '占位文字', 'theme_color_light', '#737d8c', '输入提示和弱化内容', 340, 0, 1, NULL, NULL),
('text_on_brand', '品牌色上文字', 'theme_color_light', '#ffffff', '主色按钮与品牌色背景上的文字', 350, 0, 1, NULL, NULL),
('border_color', '主要边框', 'theme_color_light', 'rgba(74, 91, 113, 0.22)', '控件和卡片的常规描边', 360, 0, 1, NULL, NULL),
('border_color_light', '弱边框', 'theme_color_light', 'rgba(74, 91, 113, 0.12)', '分隔线和低强调描边', 370, 0, 1, NULL, NULL),
('stroke_highlight', '表面高光', 'theme_color_light', 'rgba(255, 255, 255, 0.92)', '半透明表面的顶部高光', 380, 0, 1, NULL, NULL),
('focus_ring', '焦点光环', 'theme_color_light', 'rgba(15, 108, 189, 0.32)', '键盘操作时的可访问性焦点提示', 390, 0, 1, NULL, NULL),
('brand_primary', '品牌主色', 'theme_color_dark', '#479ef5', '主按钮、选中态和主要链接', 10, 0, 1, NULL, NULL),
('brand_primary_hover', '主色悬停', 'theme_color_dark', '#62abf5', '主要操作的悬停状态', 20, 0, 1, NULL, NULL),
('brand_primary_pressed', '主色按下', 'theme_color_dark', '#2886de', '主要操作的按下状态', 30, 0, 1, NULL, NULL),
('brand_cyan', '品牌青色', 'theme_color_dark', '#38d5de', '辅助品牌色和渐变终点', 40, 0, 1, NULL, NULL),
('brand_violet', '品牌紫色', 'theme_color_dark', '#9c89ff', '强调装饰和数据视觉辅助色', 50, 0, 1, NULL, NULL),
('primary_gradient_start', '渐变起点', 'theme_color_dark', '#479ef5', '主品牌渐变的起始颜色', 60, 0, 1, NULL, NULL),
('primary_gradient_end', '渐变终点', 'theme_color_dark', '#38d5de', '主品牌渐变的结束颜色', 70, 0, 1, NULL, NULL),
('color_success', '成功色', 'theme_color_dark', '#54b054', '成功、完成和正常状态', 110, 0, 1, NULL, NULL),
('color_warning', '警告色', 'theme_color_dark', '#f9a825', '提醒、等待和风险状态', 120, 0, 1, NULL, NULL),
('color_danger', '危险色', 'theme_color_dark', '#f1707b', '失败、删除和高风险状态', 130, 0, 1, NULL, NULL),
('color_info', '信息色', 'theme_color_dark', '#62abf5', '一般信息和辅助提示', 140, 0, 1, NULL, NULL),
('bg_body', '页面背景', 'theme_color_dark', '#07111f', '应用主内容区的底色', 210, 0, 1, NULL, NULL),
('bg_card', '卡片背景', 'theme_color_dark', 'rgba(14, 29, 48, 0.76)', '常规卡片和容器背景', 220, 0, 1, NULL, NULL),
('bg_card_hover', '卡片悬停', 'theme_color_dark', 'rgba(20, 40, 64, 0.90)', '可交互卡片的悬停背景', 230, 0, 1, NULL, NULL),
('bg_overlay', '遮罩背景', 'theme_color_dark', 'rgba(7, 17, 31, 0.80)', '浮层后方的半透明遮罩', 240, 0, 1, NULL, NULL),
('surface_solid', '实色表面', 'theme_color_dark', '#101d2e', '输入框、弹层等不透明表面', 250, 0, 1, NULL, NULL),
('surface_mica', '云母表面', 'theme_color_dark', 'rgba(11, 24, 41, 0.86)', '页面级柔和半透明材质', 260, 0, 1, NULL, NULL),
('surface_acrylic', '亚克力表面', 'theme_color_dark', 'rgba(17, 35, 57, 0.68)', '浮动卡片和导航半透明材质', 270, 0, 1, NULL, NULL),
('text_primary', '主要文字', 'theme_color_dark', '#f5f8fc', '标题和高强调正文', 310, 0, 1, NULL, NULL),
('text_regular', '常规文字', 'theme_color_dark', '#d6e0ec', '正文和表单内容', 320, 0, 1, NULL, NULL),
('text_secondary', '次要文字', 'theme_color_dark', '#a8b5c5', '说明、辅助信息和元数据', 330, 0, 1, NULL, NULL),
('text_placeholder', '占位文字', 'theme_color_dark', '#8391a3', '输入提示和弱化内容', 340, 0, 1, NULL, NULL),
('text_on_brand', '品牌色上文字', 'theme_color_dark', '#ffffff', '主色按钮与品牌色背景上的文字', 350, 0, 1, NULL, NULL),
('border_color', '主要边框', 'theme_color_dark', 'rgba(157, 192, 231, 0.24)', '控件和卡片的常规描边', 360, 0, 1, NULL, NULL),
('border_color_light', '弱边框', 'theme_color_dark', 'rgba(157, 192, 231, 0.13)', '分隔线和低强调描边', 370, 0, 1, NULL, NULL),
('stroke_highlight', '表面高光', 'theme_color_dark', 'rgba(209, 231, 255, 0.20)', '半透明表面的顶部高光', 380, 0, 1, NULL, NULL),
('focus_ring', '焦点光环', 'theme_color_dark', 'rgba(71, 158, 245, 0.40)', '键盘操作时的可访问性焦点提示', 390, 0, 1, NULL, NULL);
