-- 033 将液态玻璃主题的语义颜色与材质参数纳入系统变量管理。
-- INSERT IGNORE 仅补齐缺失项，保留已有安装中的管理员自定义值。

INSERT IGNORE INTO `system_variable`
  (`variable_key`, `variable_name`, `variable_type`, `variable_value`, `variable_label`, `sort_order`, `is_default`, `is_enabled`, `color`, `icon`) VALUES
('brand_primary', '品牌主色', 'theme_color_liquid_glass', '#3463ce', '主按钮、选中态和主要链接', 10, 0, 1, NULL, NULL),
('brand_primary_hover', '主色悬停', 'theme_color_liquid_glass', '#2952b3', '主要操作的悬停状态', 20, 0, 1, NULL, NULL),
('brand_primary_pressed', '主色按下', 'theme_color_liquid_glass', '#1f3f8c', '主要操作的按下状态', 30, 0, 1, NULL, NULL),
('brand_cyan', '品牌青色', 'theme_color_liquid_glass', '#22b8cf', '辅助品牌色和渐变终点', 40, 0, 1, NULL, NULL),
('brand_violet', '品牌紫色', 'theme_color_liquid_glass', '#6366f1', '强调装饰和数据视觉辅助色', 50, 0, 1, NULL, NULL),
('primary_gradient_start', '渐变起点', 'theme_color_liquid_glass', '#3463ce', '主品牌渐变的起始颜色', 60, 0, 1, NULL, NULL),
('primary_gradient_end', '渐变终点', 'theme_color_liquid_glass', '#22b8cf', '主品牌渐变的结束颜色', 70, 0, 1, NULL, NULL),
('color_success', '成功色', 'theme_color_liquid_glass', '#37a06f', '成功、完成和正常状态', 110, 0, 1, NULL, NULL),
('color_warning', '警告色', 'theme_color_liquid_glass', '#d97706', '提醒、等待和风险状态', 120, 0, 1, NULL, NULL),
('color_danger', '危险色', 'theme_color_liquid_glass', '#dc2626', '失败、删除和高风险状态', 130, 0, 1, NULL, NULL),
('color_info', '信息色', 'theme_color_liquid_glass', '#3463ce', '一般信息和辅助提示', 140, 0, 1, NULL, NULL),
('bg_body', '页面背景', 'theme_color_liquid_glass', '#f5f6f8', '应用主内容区的底色', 210, 0, 1, NULL, NULL),
('bg_card', '卡片背景', 'theme_color_liquid_glass', 'rgba(255, 255, 255, 0.65)', '常规卡片和容器背景', 220, 0, 1, NULL, NULL),
('bg_card_hover', '卡片悬停', 'theme_color_liquid_glass', 'rgba(255, 255, 255, 0.82)', '可交互卡片的悬停背景', 230, 0, 1, NULL, NULL),
('bg_overlay', '遮罩背景', 'theme_color_liquid_glass', 'rgba(245, 246, 248, 0.75)', '浮层后方的半透明遮罩', 240, 0, 1, NULL, NULL),
('surface_solid', '实色表面', 'theme_color_liquid_glass', '#ffffff', '输入框、弹层等不透明表面', 250, 0, 1, NULL, NULL),
('surface_mica', '云母表面', 'theme_color_liquid_glass', 'rgba(245, 247, 250, 0.80)', '页面级柔和半透明材质', 260, 0, 1, NULL, NULL),
('surface_acrylic', '亚克力表面', 'theme_color_liquid_glass', 'rgba(255, 255, 255, 0.52)', '浮动卡片和导航半透明材质', 270, 0, 1, NULL, NULL),
('text_primary', '主要文字', 'theme_color_liquid_glass', '#252b35', '标题和高强调正文', 310, 0, 1, NULL, NULL),
('text_regular', '常规文字', 'theme_color_liquid_glass', '#3b4453', '正文和表单内容', 320, 0, 1, NULL, NULL),
('text_secondary', '次要文字', 'theme_color_liquid_glass', '#717a88', '说明、辅助信息和元数据', 330, 0, 1, NULL, NULL),
('text_placeholder', '占位文字', 'theme_color_liquid_glass', '#9aa2af', '输入提示和弱化内容', 340, 0, 1, NULL, NULL),
('text_on_brand', '品牌色上文字', 'theme_color_liquid_glass', '#ffffff', '主色按钮与品牌色背景上的文字', 350, 0, 1, NULL, NULL),
('border_color', '主要边框', 'theme_color_liquid_glass', 'rgba(205, 210, 219, 0.72)', '控件和卡片的常规描边', 360, 0, 1, NULL, NULL),
('border_color_light', '弱边框', 'theme_color_liquid_glass', 'rgba(223, 226, 231, 0.60)', '分隔线和低强调描边', 370, 0, 1, NULL, NULL),
('stroke_highlight', '表面高光', 'theme_color_liquid_glass', 'rgba(255, 255, 255, 0.95)', '半透明表面的顶部高光', 380, 0, 1, NULL, NULL),
('focus_ring', '焦点光环', 'theme_color_liquid_glass', 'rgba(52, 99, 206, 0.35)', '键盘操作时的可访问性焦点提示', 390, 0, 1, NULL, NULL),
('glass_renderer_mode', '渲染模式', 'theme_color_liquid_glass', 'auto', '自动选择增强折射或兼容毛玻璃', 510, 0, 1, NULL, NULL),
('glass_refraction', '折射强度', 'theme_color_liquid_glass', '56', '控制边缘背景位移强度', 520, 0, 1, NULL, NULL),
('glass_bevel', '斜面宽度', 'theme_color_liquid_glass', '22', '控制产生折射与高光的边缘范围', 530, 0, 1, NULL, NULL),
('glass_blur', '光学模糊', 'theme_color_liquid_glass', '0.35', '增强折射路径中的轻微模糊', 540, 0, 1, NULL, NULL),
('glass_dispersion', '色散强度', 'theme_color_liquid_glass', '1.2', '控制边缘 RGB 通道的微弱分离', 550, 0, 1, NULL, NULL),
('glass_radius', '表面圆角', 'theme_color_liquid_glass', '24', '控制主壳层和玻璃卡片的圆角', 560, 0, 1, NULL, NULL),
('glass_tint', '材质着色', 'theme_color_liquid_glass', 'rgba(255,255,255,0.018)', '叠加在实时背景上的低透明度颜色', 570, 0, 1, NULL, NULL),
('glass_surface_opacity', '表面透明度', 'theme_color_liquid_glass', '0.65', '控制普通业务卡片的透明表面强度', 580, 0, 1, NULL, NULL),
('glass_backdrop_blur', '兼容模糊', 'theme_color_liquid_glass', '16', 'CSS 降级路径与普通业务表面的背景模糊', 590, 0, 1, NULL, NULL),
('glass_saturation', '背景饱和度', 'theme_color_liquid_glass', '108', '控制玻璃后方内容的饱和度百分比', 600, 0, 1, NULL, NULL);
